<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebApplication1.controller\WebApplication1.controller.csproj" />
    <ProjectReference Include="..\WebApplication1.repository\WebApplication1.repository.csproj" />
    <ProjectReference Include="..\WebApplication1.service\WebApplication1.service.csproj" />
  </ItemGroup>

</Project>
