<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VolleyballApp.model\VolleyballApp.model.csproj" />
    <ProjectReference Include="..\VolleyballApp.repository\VolleyballApp.repository.csproj" />
  </ItemGroup>

</Project>
